sudo: false

cache:
  directories:
    - $HOME/cargo
    - $TRAVIS_BUILD_DIR/examples/target

install:
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.40.3/hugo_0.40.3_Linux-64bit.tar.gz | tar xzvf -

matrix:
  include:
    - env:
      - TASK=build
      script: ./hugo
    - env:
      - TASK=check
      language: rust
      script: cd examples; cargo check

deploy:
  provider: script
  script: bash .deploy.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = "false" && $TASK = "build"
