DefaultContentLanguage = "en"
enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = "UA-110322332-1"
pygmentsUseClasses = true
pygmentsCodeFences = true
baseURL = "https://actix.rs/"

[languages.en]
    title = "actix"
    languageCode = "en-us"
    weight = 1
[languages.cn]
    title = "actix"
    languageCode = "zh-cn"
    weight = 2

[params]
actixVersion = "0.5"
actixWebVersion = "0.6"
