[workspace]
members = [
  "application",
  "easy-form-handling",
  "flexible-responders",
  "getting-started",
  "main-example",
  "powerful-extractors",
  "request-routing",
  "server",
  "url-dispatch",
  "responder-trait",
  "either"
]
exclude = [
  "request-handlers",
  "async-handlers",
  "extractors",
]
